# Generated by Django 5.2.9 on 2025-12-07 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-popularity_score']},
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflow',
            name='country',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='platform',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Forum', 'Forum'), ('GoogleTrends', 'GoogleTrends')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='popularity_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow',
            field=models.CharField(max_length=500),
        ),
    ]
